version: '3.8'

services:
  postgres-db-product:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-product
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-product:/var/lib/postgresql/data
    networks:
      - fiap-lanchonet-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data                # persiste objetos
    ports:
      - "9000:9000"                     # API S3-compatible
      - "9001:9001"                     # Console web
    command: server /data --console-address ":9001"

  fiap-lanches-product-api:
    build:
     context: .
     dockerfile: ./Dockerfile
    hostname: fiap-lanches-product-api
    ports:
      - "8082:8082"
    volumes:
      - fiap-lanches-product-api:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db-product
    networks:
      - fiap-lanchonet-network
        
networks:
  fiap-lanchonet-network:
    external: true

volumes:
  postgres-db-product:
    driver: local
  fiap-lanches-product-api:
    driver: local
  minio-data:
    driver: local
