version: '3.8'

services:
  postgres-db-product:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product
    ports:
      - "5434:5432"
    volumes:
      - postgres-db-product:/var/lib/postgresql/data
    networks:
      - green-food-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data                # persiste objetos
    ports:
      - "9000:9000"                     # API S3-compatible
      - "9001:9001"                     # Console web
    command: server /data --console-address ":9001"
    networks:
      - green-food-network

  ms-gf-product-service-v1:
    image: dalexandrias/ms-gf-product-service-v1:main
    ports:
      - "8082:8082"
    volumes:
      - ms-gf-product-service-v1:/var/lib/products/data
    depends_on:
      - postgres-db-product
    networks:
      - green-food-network

networks:
  green-food-network:
    external: true

volumes:
  postgres-db-product:
    driver: local
  ms-gf-product-service-v1:
    driver: local
  minio-data:
    driver: local
