apiVersion: v1
kind: Service
metadata:
  name: product-node-port-svc
  namespace: fiap-lanches-api
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30002
  selector:
    app: fiap-lanches-product-api
  type: NodePort